#pragma once

// Common contract shared by every wingchun extension shared library
// (kf_sim, kf_ctp, ...). An extension named <name> is a shared library
// (kf_<name>.dll on Windows / libkf_<name>.so on Linux) exporting fixed C
// entry points generated by the KF_EXTENSION_DEFINE_*_FACTORY macros:
//
//   kf_create_trader        -> new <TraderClass>(vendor)
//   kf_destroy_trader       -> delete <TraderClass>
//   kf_create_market_data   -> new <MarketDataClass>(vendor)
//   kf_destroy_market_data  -> delete <MarketDataClass>
//
// The same symbol names are reused by every extension; this is safe because
// host apps (kf_md / kf_td) always resolve them through the handle of the
// specific library they loaded (dlsym/GetProcAddress are per-handle) and
// libraries are loaded with RTLD_LOCAL, so even several extensions loaded
// into one process cannot interpose each other's symbols.
//
// Adding a new extension therefore needs no host code changes: create
// brokers/<name>/ that links kungfu and registers its classes with the two
// define macros.
//
// Lifetime: the host owns the returned service through a std::shared_ptr
// whose custom deleter is kf_destroy_*, so objects are always destroyed in
// the module that allocated them. Extension libraries are never unloaded
// during process lifetime, so deferred destruction is safe.

#include <string>

namespace kungfu::wingchun::broker {
class Trader;
class TraderVendor;
class MarketData;
class MarketDataVendor;
} // namespace kungfu::wingchun::broker

#if defined(_WIN32)
#define KF_EXTENSION_EXPORT __declspec(dllexport)
#else
#define KF_EXTENSION_EXPORT __attribute__((visibility("default")))
#endif

namespace kungfu::wingchun::extension {

using CreateTraderFn = broker::Trader *(*)(broker::TraderVendor *);
using DestroyTraderFn = void (*)(broker::Trader *);
using CreateMarketDataFn = broker::MarketData *(*)(broker::MarketDataVendor *);
using DestroyMarketDataFn = void (*)(broker::MarketData *);

/// Fixed C symbol names exported by every extension library.
inline constexpr const char *kTraderFactorySymbol = "kf_create_trader";
inline constexpr const char *kDestroyTraderSymbol = "kf_destroy_trader";
inline constexpr const char *kMarketDataFactorySymbol = "kf_create_market_data";
inline constexpr const char *kDestroyMarketDataSymbol = "kf_destroy_market_data";

} // namespace kungfu::wingchun::extension

/// Defines the kf_create_trader / kf_destroy_trader C entry points for
/// trader_class (a kungfu::wingchun::broker::Trader subclass).
#define KF_EXTENSION_DEFINE_TRADER_FACTORY(trader_class)                                      \
  extern "C" KF_EXTENSION_EXPORT kungfu::wingchun::broker::Trader *kf_create_trader(          \
      kungfu::wingchun::broker::TraderVendor *vendor) {                                       \
    return new trader_class(*vendor);                                                         \
  }                                                                                           \
  extern "C" KF_EXTENSION_EXPORT void kf_destroy_trader(                                      \
      kungfu::wingchun::broker::Trader *instance) {                                           \
    delete instance;                                                                          \
  }

/// Defines the kf_create_market_data / kf_destroy_market_data C entry points
/// for market_data_class (a kungfu::wingchun::broker::MarketData subclass).
#define KF_EXTENSION_DEFINE_MARKET_DATA_FACTORY(market_data_class)                            \
  extern "C" KF_EXTENSION_EXPORT kungfu::wingchun::broker::MarketData *kf_create_market_data( \
      kungfu::wingchun::broker::MarketDataVendor *vendor) {                                   \
    return new market_data_class(*vendor);                                                    \
  }                                                                                           \
  extern "C" KF_EXTENSION_EXPORT void kf_destroy_market_data(                                 \
      kungfu::wingchun::broker::MarketData *instance) {                                       \
    delete instance;                                                                          \
  }
