[supervisord]
logfile = %(ENV_HOME)s/.kungfu-cpp/log/supervisord.log
logfile_maxbytes = 50MB
logfile_backups = 10
loglevel = info
pidfile = %(ENV_HOME)s/.kungfu-cpp/supervisord.pid
nodaemon = false
directory = %(here)s/..

[supervisorctl]
serverurl = unix:///tmp/kungfu_supervisor.sock

[unix_http_server]
file = /tmp/kungfu_supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:kf_master]
command = %(here)s/../build/Release/kf_master
priority = 10
startsecs = 2
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_master.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_master.err.log

[program:kf_cached]
command = %(here)s/../build/Release/kf_cached
priority = 15
startsecs = 2
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_cached.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_cached.err.log

[program:kf_ledger]
command = %(here)s/../build/Release/kf_ledger
priority = 15
startsecs = 2
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_ledger.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_ledger.err.log

[program:kf_md_sim]
command = %(here)s/../build/Release/kf_md --group sim --name sim
priority = 20
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_md_sim.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_md_sim.err.log

[program:kf_td_sim]
command = %(here)s/../build/Release/kf_td --group sim --name sim --source sim
priority = 20
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_td_sim.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_td_sim.err.log

[program:kf_strategy]
command = %(here)s/../build/Release/kf_strategy --group sim --name sim
priority = 30
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_strategy.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_strategy.err.log
