[supervisord]
logfile = %(ENV_HOME)s/.kungfu-cpp/log/supervisord.log
logfile_maxbytes = 50MB
logfile_backups = 10
loglevel = info
pidfile = %(ENV_HOME)s/.kungfu-cpp/supervisord.pid
nodaemon = true
directory = %(here)s/..

[supervisorctl]
serverurl = unix:///tmp/kungfu_supervisor.sock

[unix_http_server]
file = /tmp/kungfu_supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:kf_master]
command = %(here)s/../build-linux/src/services/master/kf_master %(here)s/kungfu.toml
priority = 10
startsecs = 2
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_master.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_master.err.log

[program:kf_md_sim]
command = %(here)s/../build-linux/src/wingchun/kf_md_sim %(here)s/kungfu.toml
priority = 20
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_md_sim.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_md_sim.err.log

[program:kf_td_sim]
command = %(here)s/../build-linux/src/wingchun/kf_td_sim %(here)s/kungfu.toml
priority = 20
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_td_sim.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_td_sim.err.log

[program:kf_strategy]
command = %(here)s/../build-linux/examples/kf_strategy %(here)s/kungfu.toml
priority = 30
startsecs = 3
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_strategy.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_strategy.err.log

[program:kf_api]
command = %(here)s/../build-linux/src/services/api/kf_api %(here)s/kungfu.toml
priority = 40
startsecs = 2
autorestart = true
stdout_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_api.log
stderr_logfile = %(ENV_HOME)s/.kungfu-cpp/log/kf_api.err.log
