test_ngg_http_client:
	g++ -g -o test_nng_http_client.out nng_http_client.cpp test_nng_http_client.cpp -I. -I../../3rdparty/nng/include -L../../build/3rdparty/nng -lnng


.PHONY: test_ngg_http_client