if(WIN32)
    add_definitions(-DKUNGFU_WIN32)
    add_definitions(-D_WIN32_WINNT=0x0A00)
    add_definitions(-DNOMINMAX)
    add_definitions(-DWIN32_LEAN_AND_MEAN)
else()
    add_definitions(-DKUNGFU_POSIX)
endif()

if(MSVC)
    add_compile_options(/utf-8 /permissive- /bigobj /W3 /Zc:__cplusplus)
    add_compile_options(/wd4244 /wd4267 /wd4996)
else()
    add_compile_options(-Wall -Wextra -Wno-unused-parameter)
endif()
